---

- name: Debian | Install bind9
  ansible.builtin.apt:
    name: "{{ bind_pkgs }}"
    state: present
    update_cache: yes
  register: pkg_result
  until: pkg_result is success

- name: Import bind-apparmor
  ansible.builtin.import_tasks: bind-apparmor.yml

- name: Import resolvconf
  ansible.builtin.include_tasks: resolvconf.yml
  when: not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker")

- name: Ensure write access to {{ bind_etc }}
  ansible.builtin.file:
    mode: g+w
    group: "{{ bind_user }}"
    state: directory
    path: "{{ bind_etc }}"
