---
- name: Get hash and serial for existing reverse zone
  ansible.builtin.slurp:
    path: "{{ bind_etc }}/db.rev.{{ item | ipmangle }}zone"
  register: bind__zone_file
  changed_when: false
  failed_when: false

- name: Create reverse zone files
  ansible.builtin.template:
    src: "reverse.zone.j2"
    # dest: "{{ bind_etc }}/db.rev.{{ item | reverse_lookup_zone }}.zone"
    dest: "{{ bind_etc }}/db.rev.{{ item | ipmangle }}zone"
    owner: root
    group: "{{ bind_user }}"
    mode: '0644'
    backup: yes
    # validate: "named-checkzone {{ item | reverse_lookup_zone }} %s"
    validate: "named-checkzone {{ item | ipmangle }} %s"
  vars:
    bind__zone_id: "{{ bind__zone_file['content'] | default('') | b64decode | regex_search('^; Ansible Hash: (.+) (.+)$', '\\1', '\\2', multiline=True) }}"
  notify:
    - Restart bind
