---
## inspired from
## https://www.sbarjatiya.com/notes_wiki/index.php/Ansible_named-server_role_for_both_public_and_private_DNS
##      https://github.com/bertvv/ansible-role-bind/tree/master

- name: Get hash and serial for existing zone {{ zone.vars.bind_zone_name }}
  ansible.builtin.slurp:
    path: "{{ bind_etc }}/db.{{ zone.vars.bind_zone_name }}.zone"
  register: bind__zone_file
  changed_when: false
  failed_when: false

- name: Create zone forward files
  ansible.builtin.template:
    src: "forward.zone.j2"
    dest: "{{ bind_etc }}/db.{{ item }}.zone"
    owner: root
    group: "{{ bind_user }}"
    mode: '0644'
    backup: yes
    validate: "named-checkzone {{ item }} %s"
  with_items:
    - "{{ zone.vars.bind_zone_name }}"
  vars:
    bind__zone_id: "{{ bind__zone_file['content'] | default('') | b64decode | regex_search('^; Ansible Hash: (.+) (.+)$', '\\1', '\\2', multiline=True) }}"
  notify:
    - Restart bind
  when:
    - zone.vars.bind_zone_type != 'secondary'
    - zone.vars.bind_zone_type != 'forward'

- name: Create reverse zones
  ansible.builtin.include_tasks: zones-reverse.yml
  with_items: "{{ zone.vars.bind_zone_networks }}"
  when:
    - zone.vars.bind_zone_type != 'secondary'
    - zone.vars.bind_zone_type != 'forward'

- name: Ensure named.conf.local-zones present
  ansible.builtin.template:
    src: "named-zones.conf.local.j2"
    dest: "{{ bind_etc }}/named.conf.local-zone-{{ zone.vars.bind_zone_name }}"
    owner: root
    group: "{{ bind_user }}"
    mode: '0644'
    backup: yes
  notify:
    - Restart bind
